export const USER_LOADING ="USER_LOADING";
export const LOGIN_USER="LOGIN_USER";
export const REGISTER_USER="REGISTER_USER";
export const LOGOUT_USER="LOGOUT_USER";
export const GET_AUTH_USER="GET_AUTH_USER";
export const AUTH_ERRORS="AUTH_ERRORS";
